version: '3.8'
services:


#------------------------ Refael Server ---------------------------    
  refael:
    container_name: refael
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80 
    restart: unless-stopped
    ports:
      - 80:80
      - 7000:7000
      - 5000:5000